# frozen_string_literal: true
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: MumbleUDP.proto

require 'google/protobuf'


descriptor_data = "\n\x0fMumbleUDP.proto\x12\tMumbleUDP\"\xc2\x01\n\x05\x41udio\x12\x10\n\x06target\x18\x01 \x01(\rH\x00\x12\x11\n\x07\x63ontext\x18\x02 \x01(\rH\x00\x12\x16\n\x0esender_session\x18\x03 \x01(\r\x12\x14\n\x0c\x66rame_number\x18\x04 \x01(\x04\x12\x11\n\topus_data\x18\x05 \x01(\x0c\x12\x17\n\x0fpositional_data\x18\x06 \x03(\x02\x12\x19\n\x11volume_adjustment\x18\x07 \x01(\x02\x12\x15\n\ris_terminator\x18\x10 \x01(\x08\x42\x08\n\x06Header\"\xa6\x01\n\x04Ping\x12\x11\n\ttimestamp\x18\x01 \x01(\x04\x12$\n\x1crequest_extended_information\x18\x02 \x01(\x08\x12\x19\n\x11server_version_v2\x18\x03 \x01(\x04\x12\x12\n\nuser_count\x18\x04 \x01(\r\x12\x16\n\x0emax_user_count\x18\x05 \x01(\r\x12\x1e\n\x16max_bandwidth_per_user\x18\x06 \x01(\rB\x15H\x01\xea\x02\x10Proto::MumbleUdpb\x06proto3"

pool = ::Google::Protobuf::DescriptorPool.generated_pool
pool.add_serialized_file(descriptor_data)

module Proto
  module MumbleUdp
    Audio = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("MumbleUDP.Audio").msgclass
    Ping = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("MumbleUDP.Ping").msgclass
  end
end
