# connection
host: 0.0.0.0
port: 64_738
ssl_cert: 'run/server.cert'
ssl_key: 'run/server.key'

# server settings
max_bandwidth: 192_000
welcome_text: 'Hello world!'
allow_html: false
message_length: 500
image_message_length: 0
max_users: 15
recording_allowed: true
max_username_length: 20
default_room: 1

# debug
debug: false
debug_web: false

# database section
users:
  - id: 0
    username: admin
    password: example

rooms:
  - id: 0
    name: Root
    parent_id: null
    position: 0
  - id: 1
    name: guest_room
    parent_id: 0
    position: 1
  - id: 2
    name: forum
    parent_id: 0
    position: 0
